apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-db-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  instances: 3
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
      failoverQuorum: true
  storage:
    size: 1Gi